# Generated by Django 3.0.5 on 2020-04-11 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190124_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 20, 36, 43, 136244), verbose_name='date published'),
        ),
    ]
