# Generated by Django 3.0.5 on 2020-04-12 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200413_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 2, 1, 9, 638068), verbose_name='date published'),
        ),
    ]
