# Generated by Django 3.0.5 on 2020-04-14 21:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200413_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='series_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 33, 16, 22587), verbose_name='date published'),
        ),
    ]
