# Generated by Django 3.0.5 on 2020-04-14 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200415_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_image',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 40, 8, 884888), verbose_name='date published'),
        ),
    ]
